org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

minecraft_version_1_20_1=1.20.1
minecraft_version_range_1_20_1=[1.20.1,1.21)
forge_version_1_20_1=47.3.12
forge_version_range_1_20_1=[47.3.12,48)
forge_loader_range_1_20_1=[47,48)

minecraft_version_1_21_1=1.21.1
minecraft_version_range_1_21_1=[1.21.1,1.22)
neoforge_version_1_21_1=21.1.240

minecraft_version_26_1_2=26.1.2
minecraft_version_range_26_1_2=[26.1.2,26.2)
neoforge_version_26_1_2=26.1.2.76

lombok_version=1.18.48

mod_id=nstutlib
mod_name=NsTut Lib
mod_license=All Rights Reserved
mod_version=0.8
mod_group_id=com.nstut.nstutlib
mod_authors=NsTut
mod_description=A library mod for NsTut's mods.
